### PR TITLE
Japanese translation update

### PR DESCRIPTION
**Pull request by Proxyer**
I have responded to your request.
I bought all the comics of this work and watched the animation, so I was able to translate it without any problems.

I thought it was difficult to understand the character in the explanation of the clothes, so I added the character name enclosed in parentheses at the end of the sentence. Please consider.

### CODE REVIEW

**Comment by sumghai** [comment]
> I thought it was difficult to understand the character in the explanation of the clothes, so I added the character name enclosed in parentheses at the end of the sentence. Please consider.

Yes, this is an excellent idea! I'll keep the character name in the apparel description for the Japanese translation.

Those two files look good - the only thing missing now is `Languages/Japanese/Keyed/Hamefura.xml`. Could you please have a look at that one as well? Thanks!

**Comment by Proxyer** [comment]
Ok! When I checked, the cause was that the backup file was being translated.
18 Oct, 2020; AM 2:47 (GMT 17:48:24 17 Oct)

**Review by sumghai — APPROVED** [review]
Excellent. Thanks again, @Proxyer! :)

**Comment by Proxyer** [comment]
Thank you for update & checked!

**Pull request merged**
